name: Clifton Hypnotherapy
favicon: null
layout_spectrum: 0.4400059280451387
typography_spectrum: 0.32414
title: Clifton Hypnotherapy Practice
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-39145417-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9383ca'
    - '#acc90c'
    - '#cacaca'
    - '#d8908d'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
