name: Clifton Hypnotherapy
favicon: null
layout_spectrum: 0.4400059280451387
typography_spectrum: 0.25858799018897116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2362221758812666
  lightness: 0.14143216609954834
  saturation: 0.8397730684373528
  rhythmicContrast: 0.04613021365366876
purpose: []
