typography_spectrum: 0.32414
color:
  brandColors:
    - '#ffffff'
    - '#9383ca'
    - '#acc90c'
    - '#cacaca'
    - '#d8908d'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/ddedf4e3-5e17-4598-97e0-c4f551f81147.png
  type: null
  appId: null
layout_spectrum: 0.64384
analytics:
  google: UA-39145417-6
  facebook: null
  twitter: null
author:
  name: Changes Welcome
  email: info@cliftonhypnotherapy.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1efda43c-1314-4f38-9703-6ebab89c7395.png
name: Clifton Hypnotherapy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Getting Started
    id: a68a7a03-19ac-4728-825c-061b60e433c8
    type: content
  - name: Clinical & Performance Enhancements
    id: 0ebf707f-54da-4eed-93e8-50426e6a4345
    type: content
  - name: Locations
    id: bd736084-4146-4c23-ac3c-2940c9061c8c
    type: content
  - name: Testimonials
    id: aa2f87dc-1c4f-4607-a4c2-b49f02a72ac2
    type: content
  - name: Fees
    id: 18cc6f6b-f802-45b2-9b6a-9422fcf25941
    type: content
  - name: Contact Us
    id: ec7d29df-f320-4c24-a8a6-d7a65c5ef66d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/12642a51-3d81-44bc-a858-0c9d40e49778.png
title: Clifton Hypnotherapy Practice
content: []
description: Performance Hypnosis & Clinical Hypnotherapy in Bristol
purpose:
  - type: phone
    url: 0117 214 0724
    label: Call Us
  - type: contact
    url: 'mailto:info@cliftonhypnotherapy.com'
    label: Email Us
